"""
Livelock Characterization via Directed Cycle Homology over Z
=============================================================

EXACT ALGEBRA
-------------
    A = ( C_1^+(H*), E_rel, {z^s} )

  (1) C_1^+(H*) -- positive cone of H_1(H*, Z), first Grigor'yan path homology.

      H_1(H*, Z) = ker(d_1) / im(d_2)
        d_1(e_{ij}) = e_j - e_i
        d_2(e_{ijk}) = e_{jk} - e_{ik} + e_{ij}

      For triangle-free H*: im(d_2) = 0, H_1 = ker(d_1) = Z^k.
      k = |E| - |V| + c   (c = connected components of refined H*).

      C_1^+ = sub-semigroup generated by simple directed cycles.
      Basis: k Z-independent simple cycles B_0,...,B_{k-1}.

  (2) E_rel: propagation RELATION on C_1^+.

      Each basis cycle B_i maps to a SET of possible images (one per
      enabling walk). Each image is a simple cycle expressible in the
      basis as a Z-linear combination. Each mapping is a bijection.

      When shadows have unique witnesses, E_rel is a function (single
      image per basis cycle) and rho(E) is a permutation matrix over Z.
      When shadows have multiple witnesses, E_rel is many-valued.

  (3) z^s: cyclic shift. ALWAYS defined for every mapping.

      The enabling walk for B_i is always a simple cycle SC_j (verified).
      The shift z^s records the rotation: walk = SC_j rotated by s positions.
      This holds whether the basis decomposition of SC_j is a single B[j]
      or a compound sum like -B[1] + B[5] + B[6]. The walk is still a
      concrete simple cycle with a definite starting position.

DEPENDENCIES: livelock_complete.py
"""

import sys, os
for p in ['.', '/mnt/user-data/outputs', os.path.dirname(os.path.abspath(__file__))]:
    if p not in sys.path: sys.path.insert(0, p)

from livelock_final import (
    fixed_point, find_simple_cycles, enabling_walks, check_self_disabling
)
from collections import defaultdict


# ===================================================================
#  Graph construction
# ===================================================================

def _build_H(L):
    Kf = sorted(L); n = len(Kf)
    H = [[0]*n for _ in range(n)]
    for i, ti in enumerate(Kf):
        for j, tj in enumerate(Kf):
            if tj[1] == ti[2]: H[i][j] = 1
    return H, Kf


def refine_H(H, Kf, L_pred):
    n = len(Kf); ow = {(t[1], t[2]) for t in L_pred}
    Hr = [[0]*n for _ in range(n)]; dead = []
    for i in range(n):
        for j in range(n):
            if not H[i][j]: continue
            s = (Kf[i][0], Kf[j][0])
            if s in ow: Hr[i][j] = 1
            else: dead.append((Kf[i], Kf[j], s))
    return Hr, dead


def connected_components(H, n):
    adj = [set() for _ in range(n)]
    for i in range(n):
        for j in range(n):
            if H[i][j]: adj[i].add(j); adj[j].add(i)
    visited = [False]*n; count = 0
    for s in range(n):
        if visited[s]: continue
        count += 1; stack = [s]
        while stack:
            v = stack.pop()
            if visited[v]: continue
            visited[v] = True
            for u in adj[v]:
                if not visited[u]: stack.append(u)
    return count


# ===================================================================
#  Edge indexing
# ===================================================================

def build_edges(H, Kf):
    edges = []; e2i = {}
    for i in range(len(Kf)):
        for j in range(len(Kf)):
            if H[i][j]:
                e = (Kf[i], Kf[j])
                e2i[e] = len(edges)
                edges.append(e)
    return edges, e2i


def cycle_to_zvec(cycle, e2i, m):
    v = [0] * m
    N = len(cycle)
    for k in range(N):
        e = (cycle[k], cycle[(k+1) % N])
        if e in e2i: v[e2i[e]] += 1
    return v


# ===================================================================
#  Z-linear algebra
# ===================================================================

def z_row_reduce(vectors):
    if not vectors: return [], [], 0
    n = len(vectors); m = len(vectors[0])
    mat = [v[:] for v in vectors]
    origin = list(range(n)); pivots = []
    for col in range(m):
        best = -1
        for r in range(len(pivots), n):
            if mat[r][col] != 0:
                if best < 0 or abs(mat[r][col]) < abs(mat[best][col]): best = r
        if best < 0: continue
        pr = len(pivots)
        mat[best], mat[pr] = mat[pr], mat[best]
        origin[best], origin[pr] = origin[pr], origin[best]
        if mat[pr][col] < 0: mat[pr] = [-x for x in mat[pr]]
        changed = True
        while changed:
            changed = False
            for r in range(n):
                if r == pr or mat[r][col] == 0: continue
                q = mat[r][col] // mat[pr][col]
                if q != 0:
                    mat[r] = [mat[r][j] - q * mat[pr][j] for j in range(m)]
                    changed = True
                if mat[r][col] != 0 and abs(mat[r][col]) < abs(mat[pr][col]):
                    mat[r], mat[pr] = mat[pr], mat[r]
                    origin[r], origin[pr] = origin[pr], origin[r]
                    if mat[pr][col] < 0: mat[pr] = [-x for x in mat[pr]]
                    changed = True
        pivots.append(pr)
    return [origin[pr] for pr in pivots], mat, len(pivots)


def z_decompose(target, basis_vecs):
    k = len(basis_vecs); m = len(target)
    if k == 0: return None
    aug = [bv[:] + [1 if i == j else 0 for j in range(k)] for i, bv in enumerate(basis_vecs)]
    aug.append(target[:] + [0]*k)
    nr = k + 1; nc = m + k; pmap = {}
    for col in range(m):
        best = -1
        for r in range(len(pmap), nr):
            if aug[r][col] != 0:
                if best < 0 or abs(aug[r][col]) < abs(aug[best][col]): best = r
        if best < 0: continue
        pr = len(pmap)
        aug[best], aug[pr] = aug[pr], aug[best]
        if aug[pr][col] < 0: aug[pr] = [-x for x in aug[pr]]
        changed = True
        while changed:
            changed = False
            for r in range(nr):
                if r == pr or aug[r][col] == 0: continue
                q = aug[r][col] // aug[pr][col]
                if q != 0:
                    aug[r] = [aug[r][j] - q * aug[pr][j] for j in range(nc)]
                    changed = True
                if aug[r][col] != 0 and abs(aug[r][col]) < abs(aug[pr][col]):
                    aug[r], aug[pr] = aug[pr], aug[r]
                    if aug[pr][col] < 0: aug[pr] = [-x for x in aug[pr]]
                    changed = True
        pmap[col] = pr
    last = aug[nr - 1]
    if any(last[j] != 0 for j in range(m)): return None
    coeffs = [-last[m + i] for i in range(k)]
    check = [0] * m
    for i in range(k):
        for j in range(m): check[j] += coeffs[i] * basis_vecs[i][j]
    return coeffs if check == target else None


# ===================================================================
#  Main computation
# ===================================================================

def compute_algebra(L_star, verbose=True):
    H_raw, Kf = _build_H(L_star)
    H, dead = refine_H(H_raw, Kf, L_star)
    edges, e2i = build_edges(H, Kf)
    nE = len(edges); nV = len(Kf)
    nC = connected_components(H, nV)
    k_expected = nE - nV + nC

    if verbose:
        print(f"\n  H*: |V|={nV}, |E|={nE}, components={nC}")
        print(f"  k = |E|-|V|+c = {nE}-{nV}+{nC} = {k_expected}")
        if dead: print(f"  Dead H-edges: {len(dead)}")

    # Shadow analysis
    ow = defaultdict(list)
    for t in L_star: ow[(t[1], t[2])].append(t)
    is_det = all(len(v) == 1 for v in ow.values())
    if verbose:
        print(f"  Shadow deterministic: {is_det}")
        if not is_det:
            for key in sorted(ow):
                if len(ow[key]) > 1:
                    print(f"    ({key[0]},{key[1]}): {len(ow[key])} witnesses")

    # Simple cycles, basis
    simple = find_simple_cycles(H, Kf)
    svecs = [cycle_to_zvec(sc, e2i, nE) for sc in simple]
    if verbose: print(f"  Simple cycles: {len(simple)}")

    idx = sorted(range(len(simple)), key=lambda i: len(simple[i]))
    bo, _, _ = z_row_reduce([svecs[i] for i in idx])
    bidx = [idx[i] for i in bo]
    bcyc = [simple[i] for i in bidx]
    bvec = [svecs[i] for i in bidx]
    k = len(bcyc)

    if verbose:
        tag = "OK" if k == k_expected else f"MISMATCH (expected {k_expected})"
        print(f"  Z-basis: k = {k} {tag}")
        for i, bc in enumerate(bcyc):
            print(f"    B[{i}] (len={len(bc)}): "
                  f"{' -> '.join(f'({t[0]},{t[1]},{t[2]})' for t in bc)} ->")

    # Decompose all simple cycles; build reverse lookup
    scoords = {}
    coord_to_si = {}
    for si, sv in enumerate(svecs):
        c = z_decompose(sv, bvec)
        if c is not None:
            scoords[si] = c
            coord_to_si[tuple(c)] = si
    if verbose:
        print(f"  Decomposition: {len(scoords)}/{len(simple)} "
              f"{'ALL' if len(scoords) == len(simple) else 'INCOMPLETE'}")

    # ── E_rel with ALWAYS-attached shifts ──
    if verbose: print(f"\n  Propagation E_rel:")

    E_rel = {}
    for bi, bc in enumerate(bcyc):
        walks = enabling_walks(bc, L_star, H, Kf, max_walks=50)
        mappings = []
        seen = set()

        for w in walks:
            W = len(w)
            iv = cycle_to_zvec(w, e2i, nE)
            ic = z_decompose(iv, bvec)
            if ic is None: continue
            key = tuple(ic)
            if key in seen: continue
            seen.add(key)

            # Find which simple cycle the walk IS
            target_si = coord_to_si.get(key)
            target_sc = simple[target_si] if target_si is not None else None

            # Compute shift: walk = target_sc rotated by s
            shift = None
            if target_sc is not None and len(target_sc) == W:
                for s in range(W):
                    if all(w[p] == target_sc[(p + s) % W] for p in range(W)):
                        shift = s; break

            mappings.append({
                'coords': ic, 'shift': shift, 'walk': w,
                'target_si': target_si, 'target_len': W,
            })

        E_rel[bi] = mappings

        if verbose:
            active_fmt = lambda ic: ' + '.join(
                f"B[{j}]" if c == 1 else f"-B[{j}]" if c == -1 else f"{c}*B[{j}]"
                for j, c in [(j, ic[j]) for j in range(k) if ic[j] != 0]
            ) or '0'

            if len(mappings) == 1:
                mp = mappings[0]
                sh = f", z^{mp['shift']}" if mp['shift'] is not None else ""
                print(f"    E(B[{bi}]) = {active_fmt(mp['coords'])}{sh}")
            else:
                print(f"    E(B[{bi}]) -> {len(mappings)} images:")
                for mi, mp in enumerate(mappings):
                    sh = f", z^{mp['shift']}" if mp['shift'] is not None else ""
                    print(f"      {active_fmt(mp['coords'])}{sh}")

    # ── Functional case: build rho and verify Z-linearity ──
    is_func = all(len(v) == 1 for v in E_rel.values())
    if verbose: print(f"\n  E functional: {is_func}")

    rho = None; shifts = {}
    if is_func:
        rho = [[0]*k for _ in range(k)]
        for bi in range(k):
            mp = E_rel[bi][0]
            for bj in range(k): rho[bi][bj] = mp['coords'][bj]
            if mp['shift'] is not None:
                shifts[bi] = mp['shift']

        if verbose:
            print(f"  rho(E) ({k}x{k}):")
            for i in range(k):
                print(f"    [{' '.join(f'{rho[i][j]:2d}' for j in range(k))}]")

        nc = nk = 0
        for si in range(len(simple)):
            if si not in scoords: continue
            src = scoords[si]
            ws = enabling_walks(simple[si], L_star, H, Kf, max_walks=1)
            if not ws: continue
            iv = cycle_to_zvec(ws[0], e2i, nE)
            d = z_decompose(iv, bvec)
            if d is None: continue
            vr = [sum(rho[i][j] * src[i] for i in range(k)) for j in range(k)]
            nc += 1
            if vr == d: nk += 1
            elif verbose: print(f"    FAIL SC[{si}]")
        if verbose:
            print(f"  Z-linearity: {nk}/{nc} "
                  f"{'ALL CORRECT' if nk == nc else 'FAILURES'}")

    # ── Circulation Law ──
    if verbose: print(f"\n  Circulation Law:")

    # Build path through E_rel: find closed orbits via DFS
    def find_orbits_from(start, E_rel, k):
        """Find all closed orbits from 'start' via DFS over all E_rel options.
        Returns list of (orbit_indices, orbit_shifts)."""
        results = []

        def dfs(cur, path, shifts):
            for mp in E_rel.get(cur, []):
                coords = mp['coords']
                active = [j for j in range(k) if coords[j] != 0]
                if len(active) != 1 or coords[active[0]] != 1:
                    continue  # skip compound
                nxt = active[0]
                s = mp['shift'] if mp['shift'] is not None else 0
                if nxt == start:
                    results.append((list(path), shifts + [s]))
                elif nxt not in path and len(path) < k:
                    dfs(nxt, path + [nxt], shifts + [s])

        dfs(start, [start], [])
        return results

    visited = set()
    orbits = []
    for bi in range(k):
        if bi in visited: continue
        results = find_orbits_from(bi, E_rel, k)
        if not results:
            if verbose:
                print(f"    B[{bi}]: no closed orbit found")
            visited.add(bi)
            continue
        # Take shortest orbit found
        best = min(results, key=lambda r: len(r[0]))
        orb_idx, orb_shifts = best
        for b in orb_idx: visited.add(b)
        n_cycle = len(bcyc[orb_idx[0]])  # cycle length
        L = len(orb_idx)  # orbit length
        S = sum(orb_shifts) % n_cycle  # accumulated shift mod cycle length
        orbits.append({
            'indices': orb_idx, 'shifts': orb_shifts,
            'L': L, 'n': n_cycle, 'S': S,
        })

        if verbose:
            chain = " -> ".join(f"B[{b}]" for b in orb_idx)
            shifts_str = " + ".join(f"z^{s}" for s in orb_shifts)
            print(f"    Orbit: {chain} -> B[{orb_idx[0]}]")
            print(f"      L={L}, n={n_cycle}, shifts: {shifts_str}")
            print(f"      S = sum(shifts) mod n = {sum(orb_shifts)} mod {n_cycle} = {S}")
            print(f"      CL equation: K = q*{L},  |E| = q*{S} mod {n_cycle}")
            if S == 0:
                print(f"      => For any K = {L}*q: |E| = {n_cycle} (full cycle)")
                print(f"      => Min K = {L}, |E| = {n_cycle}")
            else:
                from math import gcd
                period = n_cycle // gcd(S, n_cycle)
                min_K = L
                min_E = S
                print(f"      => Min K = {min_K}, |E| = {min_E}")
                print(f"      => Shift period: {period} orbits for full z^n return")

    if not is_func and verbose:
        print(f"\n  (Non-deterministic: first path chosen. Other paths may yield different orbits.)")

    return {
        'k': k, 'E_rel': E_rel, 'rho': rho, 'shifts': shifts,
        'basis_cycles': bcyc, 'basis_vecs': bvec,
        'simple': simple, 'simple_coords': scoords,
        'is_deterministic': is_det, 'is_functional': is_func,
        'orbits': orbits,
    }


def test(name, T):
    print(f"\n{'='*70}")
    print(f"  {name}")
    print(f"{'='*70}")
    sd, viol = check_self_disabling(T)
    if not sd: print(f"  Not self-disabling: {viol}"); return
    has_ll, _, ko = fixed_point(T, T, verbose=False)
    if not has_ll: print("  FREE"); return
    print(f"  L* = {sorted(ko)}")
    return compute_algebra(ko)


if __name__ == "__main__":
    m = 3
    test("3-Coloring det (m=3)",
         [(v,w,(w+1)%m) for v in range(m) for w in range(m) if w==v])
    test("Leader (m=3)", [(v,v,(v+1)%m) for v in range(m)])
    test("Simple 2-cycle (m=2)", [(0,1,0),(1,0,1)])
    test("Non-det Sum-Not-2 (m=3)",
         [(m-1-v,v,w) for v in range(m) for w in range(m) if v!=w])
    test("Maximal agreement (m=3)",
         [(v,w,v) for v in range(m) for w in range(m) if v!=w])
    test("Non-det coloring (m=3)",
         [(v,v,w) for v in range(m) for w in range(m) if v!=w])
    m = 4
    test("Non-det w+2 (m=4)",
         [(v,w,(w+2)%m) for v in range(m) for w in range(m) if v==w or w==(v+1)%m])
    print(f"\n{'='*70}\n  DONE\n{'='*70}")
