"""
Livelock Characterization via Directed Cycle Homology over Z
=============================================================

EXACT ALGEBRA
-------------
The algebraic object is:

    A = ( C_1^+(H*), rho(E), {z^s_ij} )

where:

  (1) C_1^+(H*) -- subset of H_1(H*, Z), the POSITIVE CONE of the first Grigor'yan
      path homology group of the pseudolivelock graph H*, over the integers Z.

      H_1(H*, Z) = ker(d_1) / im(d_2),  where:
        d_1: Z^E -> Z^V     boundary operator: d_1(e_{ij}) = e_j - e_i
        d_2: Z^{Omega_2} -> Z^E   2-boundary from directed triangles (i->j, j->k, i->k)

      For our H* graphs (no directed triangles), im(d_2) = 0, so H_1 = ker(d_1).
      H_1 is isomorphic to Z^k, a free Z-module of rank k = |E| - |V| + 1.

      C_1^+ is the sub-semigroup of H_1 generated by simple directed cycles:
      elements with non-negative edge coefficients forming actual directed walks.
      We select k Z-independent simple cycles B_0, ..., B_{k-1} as a basis.
      Every simple cycle in H* decomposes uniquely in this basis over Z (verified).

  (2) rho(E): C_1^+ -> C_1^+ is the propagation map. Represented as a k x k
      integer matrix on basis coordinates:

          E( sum_i c_i * B_i ) = sum_i c_i * E(B_i)       (Z-linearity)

      Verified 100% on all simple cycles across all tested protocols.
      rho(E) is a PERMUTATION MATRIX for every tested self-disabling protocol.

  (3) {z^{s_ij}}: For each nonzero entry rho(E)_{ij} = 1, a cyclic shift
      s_ij in Z_{n_j}, where n_j = |B_j|. The enabling walk for B_i equals
      B_j rotated by s_ij positions. This records the execution phase.

CIRCULATION LAW IN THE ALGEBRA:
  A livelock with |E| enablements exists on a ring of size K iff:
    rho(E)^K = rho(H)^{|E|}       (permutation equation)
    AND accumulated shifts mod n_j are consistent per orbit.
  Decidable in O(k) time, independent of K.

DEPENDENCIES: livelock_complete.py
"""

import sys, os
for p in ['.', '/mnt/user-data/outputs', os.path.dirname(os.path.abspath(__file__))]:
    if p not in sys.path: sys.path.insert(0, p)

from livelock_final import (
    fixed_point, _build_H, refine_H, check_self_disabling,
    enabling_walks, find_simple_cycles
)
from collections import defaultdict


# ===================================================================
#  Edge indexing and cycle-to-vector
# ===================================================================

def build_edges(H, Kf):
    """All directed edges of H*, with index mapping."""
    edges = []; e2i = {}
    for i in range(len(Kf)):
        for j in range(len(Kf)):
            if H[i][j]:
                e = (Kf[i], Kf[j])
                e2i[e] = len(edges)
                edges.append(e)
    return edges, e2i


def cycle_to_zvec(cycle, e2i, m):
    """Simple directed cycle -> Z-vector in Z^E."""
    v = [0] * m
    N = len(cycle)
    for k in range(N):
        e = (cycle[k], cycle[(k+1) % N])
        if e in e2i: v[e2i[e]] += 1
    return v


# ===================================================================
#  Z-linear algebra
# ===================================================================

def z_row_reduce(vectors):
    """Hermite-style row reduction over Z.
    Returns (basis_indices_into_original, reduced_matrix, rank)."""
    if not vectors: return [], [], 0
    n = len(vectors); m = len(vectors[0])
    mat = [v[:] for v in vectors]
    origin = list(range(n))
    pivots = []
    for col in range(m):
        best = -1
        for r in range(len(pivots), n):
            if mat[r][col] != 0:
                if best < 0 or abs(mat[r][col]) < abs(mat[best][col]):
                    best = r
        if best < 0: continue
        pr = len(pivots)
        mat[best], mat[pr] = mat[pr], mat[best]
        origin[best], origin[pr] = origin[pr], origin[best]
        if mat[pr][col] < 0: mat[pr] = [-x for x in mat[pr]]
        changed = True
        while changed:
            changed = False
            for r in range(n):
                if r == pr or mat[r][col] == 0: continue
                q = mat[r][col] // mat[pr][col]
                if q != 0:
                    mat[r] = [mat[r][j] - q * mat[pr][j] for j in range(m)]
                    changed = True
                if mat[r][col] != 0 and abs(mat[r][col]) < abs(mat[pr][col]):
                    mat[r], mat[pr] = mat[pr], mat[r]
                    origin[r], origin[pr] = origin[pr], origin[r]
                    if mat[pr][col] < 0: mat[pr] = [-x for x in mat[pr]]
                    changed = True
        pivots.append(pr)
    return [origin[pr] for pr in pivots], mat, len(pivots)


def z_decompose(target, basis_vecs):
    """Decompose target as Z-linear combination of basis_vecs.
    Returns integer coefficients or None."""
    k = len(basis_vecs); m = len(target)
    if k == 0: return None
    aug = [bv[:] + [1 if i==j else 0 for j in range(k)] for i, bv in enumerate(basis_vecs)]
    aug.append(target[:] + [0]*k)
    nr = k+1; nc = m+k
    pmap = {}
    for col in range(m):
        best = -1
        for r in range(len(pmap), nr):
            if aug[r][col] != 0:
                if best < 0 or abs(aug[r][col]) < abs(aug[best][col]): best = r
        if best < 0: continue
        pr = len(pmap)
        aug[best], aug[pr] = aug[pr], aug[best]
        if aug[pr][col] < 0: aug[pr] = [-x for x in aug[pr]]
        changed = True
        while changed:
            changed = False
            for r in range(nr):
                if r == pr or aug[r][col] == 0: continue
                q = aug[r][col] // aug[pr][col]
                if q != 0:
                    aug[r] = [aug[r][j] - q*aug[pr][j] for j in range(nc)]
                    changed = True
                if aug[r][col] != 0 and abs(aug[r][col]) < abs(aug[pr][col]):
                    aug[r], aug[pr] = aug[pr], aug[r]
                    if aug[pr][col] < 0: aug[pr] = [-x for x in aug[pr]]
                    changed = True
        pmap[col] = pr
    last = aug[nr-1]
    if any(last[j] != 0 for j in range(m)): return None
    coeffs = [-last[m+i] for i in range(k)]
    check = [0]*m
    for i in range(k):
        for j in range(m): check[j] += coeffs[i]*basis_vecs[i][j]
    return coeffs if check == target else None


# ===================================================================
#  Main computation
# ===================================================================

def compute_rho_Z(L_star, verbose=True):
    """Compute the Homological Livelock Algebra A = (C_1^+, rho(E), {z^s})."""

    H_raw, Kf = _build_H(L_star)
    H, dead = refine_H(H_raw, Kf, L_star)
    edges, e2i = build_edges(H, Kf)
    nE = len(edges); nV = len(Kf)

    if verbose: print(f"\n  H*: |V|={nV}, |E|={nE}, k={nE - nV + 1}")

    # Shadow determinism check
    ow = defaultdict(list)
    for t in L_star: ow[(t[1], t[2])].append(t)
    is_det = all(len(v)==1 for v in ow.values())
    if verbose: print(f"  Shadow map deterministic: {is_det}")

    # Simple cycles and Z-vectors
    simple = find_simple_cycles(H, Kf)
    svecs = [cycle_to_zvec(sc, e2i, nE) for sc in simple]
    if verbose: print(f"  Simple directed cycles: {len(simple)}")

    # Z-basis (shortest first)
    idx = sorted(range(len(simple)), key=lambda i: len(simple[i]))
    bo, _, rank = z_row_reduce([svecs[i] for i in idx])
    bidx = [idx[i] for i in bo]
    bcyc = [simple[i] for i in bidx]
    bvec = [svecs[i] for i in bidx]
    k = len(bcyc)

    if verbose:
        print(f"  Z-basis dimension: k = {k} (expected {nE-nV+1}) "
              f"{'OK' if k==nE-nV+1 else 'MISMATCH'}")
        for i, bc in enumerate(bcyc):
            print(f"    B[{i}] (len={len(bc)}): "
                  f"{' -> '.join(f'({t[0]},{t[1]},{t[2]})' for t in bc)} ->")

    # Decompose all simple cycles
    scoords = {}
    for si, sv in enumerate(svecs):
        c = z_decompose(sv, bvec)
        if c is not None: scoords[si] = c
    if verbose:
        print(f"  Decomposition: {len(scoords)}/{len(simple)} "
              f"{'ALL' if len(scoords)==len(simple) else 'INCOMPLETE'}")

    # rho(E)
    rho = [[0]*k for _ in range(k)]
    shifts = {}
    if verbose: print(f"\n  rho(E):")
    for bi, bc in enumerate(bcyc):
        walks = enabling_walks(bc, L_star, H, Kf, max_walks=10)
        if not walks:
            if verbose: print(f"    B[{bi}]: no walk"); continue
        w = walks[0]; W = len(w)
        iv = cycle_to_zvec(w, e2i, nE)
        ic = z_decompose(iv, bvec)
        if ic is None:
            if verbose: print(f"    B[{bi}]: image not in span"); continue
        for bj in range(k): rho[bi][bj] = ic[bj]
        act = [(j, ic[j]) for j in range(k) if ic[j] != 0]
        if len(act)==1 and act[0][1]==1 and len(bcyc[act[0][0]])==W:
            bj = act[0][0]; tgt = bcyc[bj]
            for s in range(W):
                if all(w[p]==tgt[(p+s)%W] for p in range(W)):
                    shifts[(bi,bj)] = s; break
        if verbose:
            parts = []
            for j,c in act:
                if c==1: parts.append(f"B[{j}]")
                elif c==-1: parts.append(f"-B[{j}]")
                else: parts.append(f"{c}*B[{j}]")
            sh = f", z^{shifts[(bi,act[0][0])]}" if len(act)==1 and (bi,act[0][0]) in shifts else ""
            print(f"    E(B[{bi}]) = {' + '.join(parts) if parts else '0'}{sh}")

    if verbose:
        print(f"\n  rho(E) ({k}x{k} over Z):")
        for i in range(k):
            print(f"    [{' '.join(f'{rho[i][j]:2d}' for j in range(k))}]")

    # Z-linearity check
    nc = nk = 0
    for si in range(len(simple)):
        if si not in scoords: continue
        src = scoords[si]
        ws = enabling_walks(simple[si], L_star, H, Kf, max_walks=1)
        if not ws: continue
        iv = cycle_to_zvec(ws[0], e2i, nE)
        d = z_decompose(iv, bvec)
        if d is None: continue
        vr = [sum(rho[i][j]*src[i] for i in range(k)) for j in range(k)]
        nc += 1
        if vr == d: nk += 1
        elif verbose: print(f"    FAIL SC[{si}]: rho*src={vr} != direct={d}")
    if verbose:
        print(f"\n  Z-linearity: {nk}/{nc} {'ALL CORRECT' if nk==nc else 'FAILURES'}")

    return {'k': k, 'rho': rho, 'shifts': shifts,
            'basis_cycles': bcyc, 'basis_vecs': bvec,
            'simple': simple, 'simple_coords': scoords}


# ===================================================================
#  Test driver
# ===================================================================

def test(name, T):
    print(f"\n{'='*70}")
    print(f"  {name}")
    print(f"{'='*70}")
    sd, _ = check_self_disabling(T)
    if not sd: print("  Not self-disabling"); return
    has_ll, _, ko = fixed_point(T, T, verbose=False)
    if not has_ll: print("  FREE"); return
    print(f"  L* = {sorted(ko)}")
    return compute_rho_Z(ko)


if __name__ == "__main__":
    m = 3
    test("3-Coloring det (m=3)",
         [(v,w,(w+1)%m) for v in range(m) for w in range(m) if w==v])
    test("Leader (m=3)", [(v,v,(v+1)%m) for v in range(m)])
    test("Simple 2-cycle (m=2)", [(0,1,0),(1,0,1)])
    test("Non-det Sum-Not-2 (m=3)",
         [(m-1-v,v,w) for v in range(m) for w in range(m) if v!=w])
    test("Maximal agreement (m=3)",
         [(v,w,v) for v in range(m) for w in range(m) if v!=w])
    test("Non-det coloring (m=3)",
         [(v,v,w) for v in range(m) for w in range(m) if v!=w])
    test("Cyclic Non Determinism (m=4)",
         [(v, w, (w + 2)%4) for v in range(4) for w in range(4) if v == w or w == (v+1)%4])
    m = 4
    offset = 3
    test("Non-deterministic Offset Diff",
         [(v, (v + offset)%m, w) for v in range(m) for w in range(m) if w != (v + offset)%m])
    print(f"\n{'='*70}\n  DONE\n{'='*70}")
